---
ibm_user: was
ibm_root: "/opt/IBM"
ibm_repo: "/tmp"
ibm_shared_path: "{{ ibm_root }}/IMShared"
was_repo: "{{ ibm_repo }}/WAS"
jdk_repo: "{{ ibm_repo }}/JDK"
iim_tmp: "{{ ibm_root }}/tmp"
iim_path: "{{ ibm_root }}/InstallationManager"
was_user: "{{ ibm_user }}"
was_group: "{{ was_user }}"
state: installed
profile_state: started
was_nd: false
was_version: '9.0'
#was_mode: "{{ ibm_mode }}"
was_path: "{{ibm_root}}/WAS90/AppServer"
was_profiles_path: "{{ibm_root}}/WAS90/profiles"
entorn: "{{ ent }}"
startStop_path: "/serveis/scripts/{{ entorn }}/system/startstop"
instance: "{{ instance_name }}" 
virtual_host: "{{ vhost }}"



#was_type: "BASE"
#was_imcl_package_regex: "com.ibm.websphere.{{ was_type }}.v[0-9]+_([0-9]+.[0-9]+.[0-9]+.[0-9]+)"
#was_imcl_package_name: "com.ibm.websphere.{{ was_type }}.v90"
#jdk_imcl_package_name: "com.ibm.java.jdk.v8"


was_imcl_package_name: "com.ibm.websphere.ND.v90_9.0.5001.20190828_0616"
jdk_imcl_package_name: "com.ibm.java.jdk.v8_8.0.5035.20190422_0948"
