---
- name: Install setfacl and unzip on RedHat
  become: true
  yum:
    name: ['acl', 'unzip', 'psmisc','expect']
    state: present
    

- name: Create the {{ibm_user}} user
  become: true
  become_user: root
  user:
    name: "{{ibm_user}}"

- name: Create the {{ibm_root}} directory
  become: true
  become_user: root
  file:
    path: "{{ibm_root}}"
    state: directory
    owner: "{{ibm_user}}"
    group: "{{ibm_user}}"
    mode: 0755


- name: Create the {{ ihs_repo }} directory
  become: true
  become_user: root
  file:
    path: "{{ ihs_repo }}"
    state: directory
    owner: "{{ibm_user}}"
    group: "{{ibm_user}}"
    mode: 0755

- name: Create the {{ plg_repo }} directory
  become: true
  become_user: root
  file:
    path: "{{ plg_repo }}"
    state: directory
    owner: "{{ibm_user}}"
    group: "{{ibm_user}}"
    mode: 0755


- name: Create the {{ jdk_repo }} directory
  become: true
  become_user: root
  file:
    path: "{{ jdk_repo }}"
    state: directory
    owner: "{{ibm_user}}"
    group: "{{ibm_user}}"
    mode: 0755



- name: Descarreguem el IHS.
  get_url:
    url: "http://192.168.1.110/was90/was.repo.90501.ihs.zip"
    dest: "{{ ibm_repo }}/was.repo.90501.ihs.zip"

- name: Descarreguem els Plugins.
  get_url:
    url: "http://192.168.1.110/was90/was.repo.90501.plugins.zip"
    dest: "{{ ibm_repo }}/was.repo.90501.plugins.zip"

- name: Descarregem el JAVA.
  get_url:
    url: "http://192.168.1.110/was90/sdk.repo.8035.java8.linux.zip"
    dest: "{{ ibm_repo }}/sdk.repo.8035.java8.linux.zip"


- name: Descomprimim el IHS
  become: true
  unarchive:
    src: "{{ ibm_repo }}/was.repo.90501.ihs.zip"
    dest: "{{ ihs_repo }}"
    remote_src: yes
    group: "{{ibm_user}}"
    owner: "{{ibm_user}}"

- name: Descomprimim el jdk repo
  become: true
  unarchive:
    src: "{{ ibm_repo }}/sdk.repo.8035.java8.linux.zip"
    dest: "{{ jdk_repo }}"
    remote_src: yes
    group: "{{ibm_user}}"
    owner: "{{ibm_user}}" 

- name: Descomprimim els plugins
  become: true
  unarchive:
    src: "{{ ibm_repo }}/was.repo.90501.plugins.zip"
    dest: "{{ plg_repo }}"
    remote_src: yes
    group: "{{ibm_user}}"
    owner: "{{ibm_user}}" 



- name: Install IHS
  become: true
  #become_user: "{{ was_user }}"
  shell: "runuser -l {{ibm_user}} -c '{{ iim_path }}/tools/imcl install {{ ihs_imcl_package_name }} {{ jdk_imcl_package_name }} -repositories {{ ihs_repo }},{{ jdk_repo }} -installationDirectory {{ ihs_path }} -sharedResourcesDirectory {{ ibm_shared_path }} -accessRights nonAdmin -acceptLicense'"
 
- name: Install Plugins
  become: true
  #become_user: "{{ was_user }}"
  shell: "runuser -l {{ibm_user}} -c '{{ iim_path }}/tools/imcl install {{ plg_imcl_package_name }} {{ jdk_imcl_package_name }} -repositories {{ plg_repo }},{{ jdk_repo }} -installationDirectory {{ plg_path }} -sharedResourcesDirectory {{ ibm_shared_path }} -accessRights nonAdmin -acceptLicense'"
   

- name: Copy script to {{ startStop_path }}/ihs90/
  become: true
  copy:
    src: ihs.generic.sh
    dest: "{{ startStop_path }}/ihs90/"
    owner: "{{ibm_user}}"
    group: "root"
    mode: 0770


- name: Create symbolics links to execute scripts
  become: true
  file:
    src: "{{ startStop_path }}/ihs90/ihs.generic.sh"
    dest: '{{ item.dest }}'
    state: link
  loop:
    - { dest: "{{ startStop_path }}/ihs90/{{ web_server }}.start.sh"}
    - { dest: "{{ startStop_path }}/ihs90/{{ web_server }}.stop.sh"}
    - { dest: "{{ startStop_path }}/ihs90/{{ web_server }}.status.sh"}

- name: Copy the Template files to create a webserver
  become: true
  template:
     src: "{{ item.src }}"
     dest: "{{ ibm_repo }}/{{item.dest}}"
     owner: "{{ibm_user}}"
     group: "{{ibm_user}}"
     mode: 0755
  with_items:
    - { src: 'createWebServer.py.j2', dest: 'createWebServer.py' }
    - { src: 'createWebServer.sh.j2', dest: 'createWebServer.sh' }
    - { src: 'httpd.conf.j2', dest: 'httpd.conf.{{ web_server }}' }

- name: Copy conf files to config folder
  become: true
  copy:
    src: "{{ ibm_repo }}/httpd.conf.{{ web_server }}"
    dest: "{{ ihs_path }}/conf/httpd.conf.{{ web_server }}"
    remote_src: true
    owner: "{{ibm_user}}"
    group: "{{ibm_user}}"
    mode: 0755 



- name: Create plugin path
  become: true
  file:
    path: "{{ ihs_path }}/plugins/config/{{ web_server }}"
    state: directory
    owner: "{{ibm_user}}"
    group: "{{ibm_user}}"
    mode: 0755

- name: Create plugin-cfg.xml file
  become: true
  file:
    path: "{{ ihs_path }}/plugins/config/{{ web_server }}/plugin-cfg.xml"
    state: touch
    owner: "{{ibm_user}}"
    group: "{{ibm_user}}"
    mode: 0755

- name: Create logs path
  become: true
  file:
    path: "/var/log/{{ entorn }}/a{{virtual_host}}/httpserver90/{{ web_server }}"
    state: directory
    owner: "{{ibm_user}}"
    group: "{{ibm_user}}"
    mode: 0755

- name: Create Document Root
  become: true
  file:
    path: "/serveis/dades/{{ entorn }}/a{{ virtual_host }}/htdocs/{{ web_server }}"
    state: directory
    owner: "{{ibm_user}}"
    group: "{{ibm_user}}"
    mode: 0755

- name: Create WebServer
  become: true
  shell:  "runuser -l {{ibm_user}} -c '{{ ibm_repo }}/createWebServer.sh'"

- name: Change owner and group to was
  become: true
  file:
    path: "{{ ibm_root }}"
    state: directory
    recurse: yes
    owner: "{{ibm_user}}"
    group: "{{ibm_user}}"
    


- name: Delete the {{ ihs_repo }} directory
  become: true
  become_user: root
  file:
    path: "{{ ihs_repo }}"
    state: absent
    owner: "{{ibm_user}}"
    group: "{{ibm_user}}"
    mode: 0755

- name: Delete the {{ plg_repo }} directory
  become: true
  become_user: root
  file:
    path: "{{ plg_repo }}"
    state: absent
    owner: "{{ibm_user}}"
    group: "{{ibm_user}}"
    mode: 0755


- name: Delete the {{ jdk_repo }} directory
  become: true
  become_user: root
  file:
    path: "{{ jdk_repo }}"
    state: absent
    owner: "{{ibm_user}}"
    group: "{{ibm_user}}"
    mode: 0755

